version: '3'

services:
  # PHP Application Service
  php:
    container_name: php
    build:
      # Build Dockerfile context on the current directory
      context: .
      dockerfile: Dockerfile 
    volumes:
      # local ./src directory contains PHP code
      # Mount it to the to /var/www/html on the container
      - ./src:/var/www/html
      - ./apache/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      # Ensure MySQL is started before PHP
      - database-container
    networks:
      - web
    restart: always
    environment:
      - APACHE_SERVER_NAME=localhost

  # Database Container Service
  database-container:
    image: mysql:8.0
    container_name: database-container
    restart: always
    volumes:
      - ./mysql/mail_schema.sql:/docker-entrypoint-initdb.d/mail_schema.sql
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: mail
      MYSQL_USER: ${MYSQL_USER:-mailuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mailuserpass}
    networks:
      - mail_network

  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database-container
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
      APACHE_SERVER_NAME: phpmyadmin
    depends_on:
      - database-container
    networks:
      - mail_network

  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: openldap
    ports: 
      - "389:389"
      - "636:636"
    volumes:
      - ./data/certificates:/container/service/slapd/assets/certs
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
    environment: 
      - LDAP_ORGANISATION=ramhlocal
      - LDAP_DOMAIN=ramhlocal.com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin_pass
      - LDAP_CONFIG_PASSWORD=config_pass
      - "LDAP_BASE_DN=dc=ramhlocal,dc=com"
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=ramhlocal.com.ca.crt
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=user-ro
      - LDAP_READONLY_USER_PASSWORD=ro_pass
    networks:
      - web
    restart: always
  
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports: 
      - "81:80"
    environment: 
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - web
    restart: always
    
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
    depends_on:
      - postfix
      - dovecot
    networks:
      - mail_network

  # Почтовый сервер Postfix 
  postfix:
    build: ./postfix
    container_name: postfix
    restart: always
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
    volumes:
      - ./postfix/config:/etc/postfix/config
      - ./postfix/certs:/etc/postfix/certs
      - ./postfix/log:/var/log
      - shared_data:/var/shared
    depends_on:
      - database-container
    environment:
      MYSQL_SERVER: database-container
      MYSQL_DATABASE: mail
      MYSQL_USER: ${MYSQL_USER:-mailuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mailuserpass}
      HOSTNAME: ${MAIL_DOMAIN:-mail.example.com}
      TZ: ${TZ:-Europe/Moscow}
    networks:
      mail_network:
        ipv4_address: 172.18.0.3

  # IMAP/POP3 сервер Dovecot
  dovecot:
    build: ./dovecot
    container_name: dovecot
    restart: always
    ports:
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
    volumes:
      - ./dovecot/config:/etc/dovecot
      - ./dovecot/log:/var/log
      - vmail_data:/var/vmail
      - shared_data:/var/shared
    depends_on:
      - database-container
      - postfix
    environment:
      MYSQL_SERVER: database-container
      MYSQL_DATABASE: mail
      MYSQL_USER: ${MYSQL_USER:-mailuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mailuserpass}
      POSTFIX_HOST: 172.18.0.3
      TZ: ${TZ:-Europe/Moscow}
    networks:
      - mail_network

volumes:
  mysql_data:
  vmail_data:
  shared_data:

networks:
  web:
    driver: bridge
  mail_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24